### ISSUE TITLE
mediamanager file dialog

### ISSUE THREAD

**Issue by martingabelmann** [particleKIT/dokuKIT#2]
The dialog for editig existing files is not appearing in the right place...

**Comment by michitux** [comment]
Yes, the layout of the media manager seems kind of broken. There are [_media_fullscreen.css](https://github.com/splitbrain/dokuwiki/blob/master/lib/tpl/dokuwiki/css/_media_fullscreen.css) and [_tabs.css](https://github.com/splitbrain/dokuwiki/blob/master/lib/tpl/dokuwiki/css/_tabs.css) in the default dokuwiki template that should contain most if not all styles of the media manager. Copying them might fix this.
